### ISSUE TITLE
Handle SELinux in roles (barman)?

### ISSUE THREAD

**Issue by dirkcaumueller** [EnterpriseDB/edb-ansible#151]
Dear EDB team!

I stumbled across an error regarding SELinux in status enforcing when deploying a setup of a primary + 2 standbys + 1 barman server on CentOS7. The postgres primary tried to execute the archive-command for Barman WAL archiving and failed with the following message in the Postgres logs:

```bash
ERROR: Error executing ssh: [Errno 32] Broken pipe
Exception ValueError: 'I/O operation on closed file' in <bound method _Stream.__del__ of <tarfile._Stream instance at 0x7fe3724ac830>> ignored
2021-02-09 14:15:36.383 CET [5882701] @ app= LOG:  Archivbefehl ist fehlgeschlagen mit Statuscode 2
2021-02-09 14:15:36.383 CET [5882702] @ app= DETAIL:  Der fehlgeschlagene Archivbefehl war: barman-wal-archive 192.168.1.138 primary1 pg_wal/000000010000000000000003
```

After some research I found out, that my custom location for `barman_home` ("/pgbackup/barman") resulted in SELinux prohibiting a ssh connection from the primary to the backup server. The custom location was not labeled at all as a home directory (of course! ;) ).

There are now several options (as far as I understand/know) to handle this situation and I'd like to ask for your opinion in terms of best practice and this collection:

1. Activate `usepasswd=true` in `/etc/selinux/semanage.conf` to allow SELinux to scan `etc/passwd` for the home location and label it automatically as home directory. This would result in no implementation tasks in this collection, but maybe a small comment in `edb-ansible/roles/setup_barmanserver/README.md` like:

```md
### `barman_home`

Path of the barman home directory. Backup files and archived WAL files are
stored in this root directory. Default: `/var/lib/barman`

Example:
```yaml
barman_home: '/var/lib/barman'
```.

*Please take note:* Configuration of a custom home directory requires correct context/labels for the directory and subsequent files/directories if SELinux is enforced.
```

2. Implement for barman additional tasks, e.g. the following changes in file `edb-ansible/roles/setup_barmanserver/tasks/create_user.yml`:

```yaml
- name: Test whether SELinux is enabled
  command: getenforce
  register: selinux_status

- name: Set SELinux context of custom located barman home directory
  sefcontext:
    target: "{{ barman_home }}(/.*)?"
    setype: user_home_t
    state: present
  register: barman_home_dir
  when:
    - selinux_status.stdout == 'Enforcing'
    - barman_home != barman_default_home

- name: Apply new SELinux context for custom located barman home directory
  command: "restorecon -irv {{ barman_home }}"
  when: barman_home_dir.changed
```

And add the variable `barman_default_home: "/var/lib/barman"` to file `edb-ansible/roles/setup_barmanserver/defaults/main.yml`.

3. Same like 2., but only change context for barman's `.ssh` directory to `ssh_home_t`.

4. Use same steps for barman role as described for EPAS in the [documentation](https://www.enterprisedb.com/edb-docs/d/edb-postgres-advanced-server/installation-getting-started/installation-guide-for-linux/13/using_a_package_manager_to_install_advanced_server.html#configuring-selinux-policy-to-change-the-data-directory-location-on-centos-or-redhat-7-x) in chapter 3.3.3.

Thank you!
