### ISSUE TITLE
EPAS install - override default variables

### ISSUE THREAD

**Issue by mslivonja** [EnterpriseDB/edb-ansible#152]
How to override default variables for EPAS installation.

I wan't to override default variables for init_dbserver role e.g.

```
- role: init_dbserver
      vars:
        pg_superuser: "edb_user"
        pg_userpuser_password: "edb_pass"
```

Expected behavior is: passwords are changed accordingly 
Actual: default password defined in EPAS.yml is used instead.

Variables cannot be overridden in main play because for EPAS installation because include_vars EPAS.yml  is always executed and variables are reset to their default values.

**Comment by vibhorkumar123** [comment]
You can use set_fact before calling the role.
something like given below:
```
---
- hosts: all
  name: Postgres deployement playbook
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        yum_username: ""
        yum_password: ""
        pg_superuser: "edb_user"
        pg_superuser_password: "edb_pass"

  roles:
    - role: init_dbserver
       when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```
