### ISSUE TITLE
Add `edb_audit` log directory customization support in edb-ansible

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/edb-ansible#191]
Hi, Team,

Usually when we help our customer deploying EPAS, we help them enable EDB Audit Log feature in advance.

And we usually separate `edb_audit/` directory from `$PGDATA` to avoid unnecessary disk occupation (we also separate `log/` from `$PGDATA` too).

Below is a heredoc snippet we usually use.
```
mkdir $PGDATA/../edb_audit
cat << EOF >> /pgdata/as13/data/postgresql.auto.conf
log_directory = '../log'
edb_audit = 'csv'
edb_audit_directory = '../edb_audit'
edb_filter_log.redact_password_commands = true
EOF
```

I recently try `edb-ansible` and want to improve our deployment process,
and I find that currently EDB Audit Log feature setup is not included yet.

I currently only see `pg_log` setting in [roles/init_dbserver/vars/EPAS.yml](https://github.com/EnterpriseDB/edb-ansible/blob/master/roles/init_dbserver/vars/EPAS_RedHat.yml).

It would be great to include this setting into `edb-ansible`.

Best Regards.

**Comment by vibhorkumar123** [comment]
Hi @CC-Hsu You can use variable `pg_postgres_conf_params` to set the parameters in postgresql.auto.conf.
In your playbook, you can use the variable like given below:
```
---
- hosts: all
  name: Postgres deployment playbook for reference architecture EDB-RA-2
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres
  pre_tasks:
    - name: Set edb_audit parameter
      set_fact:
          pg_postgres_conf_params:
              - name: edb_audit
                value: "csv"
              - name: edb_audit_directory
                value: "edb_audit"
              - name:  edb_filter_log.redact_password_commands
                 value: "true"

  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_replication
      when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_efm
      when: "'setup_efm' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_pemserver
      when: "'setup_pemserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_pemagent
      when: "'setup_pemagent' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_barmanserver
      when: "'setup_barmanserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_barman
      when: "'setup_barman' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: autotuning
      when: "'autotuning' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```

For more information, please refer to the link given below:
https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/manage_dbserver
