### ISSUE TITLE
Add `$HOME/.enterprisedb_profile` for enterprisedb or `$HOME/.pgsql_profile` for postgres OS accounts with edb-ansible

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/edb-ansible#192]
Hi, Support Team,

In current RPM-based PGSQL/EPAS installation, a `$HOME/.bash_profile` is provided, and inside the file it references to either `/var/lib/pgsql/.pgsql_profile` or `/var/lib/edb/.enterprisedb_profile` depending on the installation.

We usually help our customer create `.pgsql_profile` / `.enterprisedb_profile` files since it is handy and useful for users to work.

We follow `pg_env.sh` / `pgplus_env.sh` content provided by previous interactive installers.
https://www.enterprisedb.com/edb-docs/d/edb-postgres-advanced-server/installation-getting-started/installation-guide/10/EDB_Postgres_Advanced_Server_Installation_Guide.1.38.html

Below is a sample content for `.enterprisedb_profile` we currently use (slightly modified from `pgplus_env.sh`).
```
## EnterpriseDB shell environment
export EDBHOME=/var/lib/edb/
export PGDATA=/pgdata/as13/data
export PGDATABASE=edb
export PGUSER=enterprisedb
export PGPORT=5444
export PGLOCALEDIR=/usr/edb/as13/share/locale

## Shell Completion enhancement
shopt -u progcomp

## Loading global shell prompt option
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
```

Can you consider adding these files in edb-ansible?
It would be very useful for all users 😊.

Best Regards.

**Comment by vibhorkumar123** [comment]
IIRC, this used to be with one-click installers. I don't think we ship with RPMs or Debian packages.

**Comment by CC-Hsu** [comment]
Hi, vibhorkumar123,

You're right.
As far as I know, the environment variable script `pgplus_env.sh` was shipped with one-click installer, 
and in RPM packages, `.bash_profile` is provided with `.pgsql_profile` / `.enterprisedb_profile` reference instead.
In CentOS-based PGSQL13 RPM installation,
```
[postgres@pgsql13 ~]$ cat ~/.bash_profile 
[ -f /etc/profile ] && source /etc/profile
PGDATA=/var/lib/pgsql/13/data
export PGDATA
# If you want to customize your settings,
# Use the file below. This is not overridden
# by the RPMS.
[ -f /var/lib/pgsql/.pgsql_profile ] && source /var/lib/pgsql/.pgsql_profile
[postgres@pgsql13 ~]$ 
```
In CentOS-based EPAS13 RPM installation.
```
[enterprisedb@epas13 ~]$ cat ~/.bash_profile 
[ -f /etc/profile ] && source /etc/profile
PGDATA=/var/lib/edb/as13/data
export PGDATA
# If you want to customize your settings,
# Use the file below. This is not overridden
# by the RPMS.
[ -f /var/lib/edb/.enterprisedb_profile ] && source /var/lib/edb/.enterprisedb_profile
[enterprisedb@epas13 ~]$
```

I guess many users might forget this goodie.

So I feel that `edb-ansible` can help on providing `.pgsql_profile` or `.enterprisedb_profile` automatically, and make users' life easier.

Best Regards.

**Comment by vibhorkumar123** [comment]
We could add this. However, I am trying to understand the benefit of this. When you do the installation using RPM, RPM creates the symbolic links of the commonly used binaries in `/usr/bin` and for start-stop recommended practice, use `systemctl service,` which is aware of PGDATA.

**Comment by CC-Hsu** [comment]
Hi, vibhorkumar123,

Usually we add this environment variable file for customers since DBAs need:
1. Advanced EPAS/PGSQL commands in `/usr/edb/asXX/bin/` or `/usr/pgsql/XX/bin/`
2. Access DB config files and logs quickly, especially when `PGDATA` is not in the default location
3. Customized `PGPORT` & `PGDATABASE` and they don't to type connection option every time

Besides of these shell environment variable files, we also add some basic content to `~/.psqlrc` for our customers.
```
\pset null '(NULL)'
\timing on
```

If edb-ansible can also provide it, it would be beneficial for newcomers.

**Comment by vibhorkumar123** [comment]
Hi @jt-edb What do you think?

**Comment by jt-edb** [comment]
> Hi @jt-edb What do you think?

Providing shell profile and `psql` configuration files is an interesting feature.

**Comment by jt-edb** [comment]
@CC-Hsu could please take a look at this PR https://github.com/EnterpriseDB/edb-ansible/pull/198

Please find below a playbook example using it:
```yaml
---
- hosts: primary,standby
  name: Create shell profile and ~/.psqlrc
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - set_fact:
        pg_version: 13
        pg_type: "EPAS"
        psqlrc_content: |
          \pset null '(NULL)'
          \timing on
        shell_profile_content: |
          ## EnterpriseDB shell environment
          export EDBHOME=/var/lib/edb/
          export PGDATA=/pgdata/as13/data
          export PGDATABASE=edb
          export PGUSER=enterprisedb
          export PGPORT=5444
          export PGLOCALEDIR=/usr/edb/as13/share/locale

          ## Shell Completion enhancement
          shopt -u progcomp

          ## Loading global shell prompt option
          # Source global definitions
          if [ -f /etc/bashrc ]; then
              . /etc/bashrc
          fi
          # Get the aliases and functions
          if [ -f ~/.bashrc ]; then
              . ~/.bashrc
          fi

  roles:
    - role: manage_dbserver
```

**Comment by CC-Hsu** [comment]
Hi, jt-edb,

Thanks for your improvement 😊.

I tried it and it works as expected, adding these files to the right place.

But I try to substitute some information with some variables further, I find some other minor issues.

I specify EPAS 13 on CentOS 8 Stream (to mimic RHEL 8.x), with variable substitution.

Below is my playbook YAML.
```
---
- hosts: primary,standby
  name: EDB deployment playbook
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "EPAS"
        repo_username: "ooooo"
        repo_password: "xxxxxx"
        use_hostname: true
        disable_logging: false
        psqlrc_content: |
          \pset null '(NULL)'
          \timing on
        shell_profile_content: |
          ## EnterpriseDB shell environment
          export EDBHOME={{ pg_user_home }}
          export PGDATA={{ pg_data }}
          export PGDATABASE=edb
          export PGUSER=enterprisedb
          export PGPORT={{ pg_port }}
          export PGLOCALEDIR=/usr/edb/{{ pg_version }}/share/locale

          ## Shell Completion enhancement
          shopt -u progcomp

          ## Loading global shell prompt option
          # Source global definitions
          if [ -f /etc/bashrc ]; then
              . /etc/bashrc
          fi
          # Get the aliases and functions
          if [ -f ~/.bashrc ]; then
              . ~/.bashrc
          fi


  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_replication
      when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: manage_dbserver
      when: "'manage_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"

```

But output files shows incorrect result, replacing `as13` with `12` and `/var/lib/edb` with `/var/lib/pgsql`.
```
[enterprisedb@edb1 ~]$ cat ~/.enterprisedb_profile 
## EnterpriseDB shell environment
export EDBHOME=/var/lib/pgsql
export PGDATA=/var/lib/pgsql/12/data
export PGDATABASE=edb
export PGUSER=enterprisedb
export PGPORT=5432
export PGLOCALEDIR=/usr/edb/12/share/locale

## Shell Completion enhancement
shopt -u progcomp

## Loading global shell prompt option
# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
[enterprisedb@edb1 ~]$ cat ~/.psqlrc               
\pset null '(NULL)'
\timing on
[enterprisedb@edb1 ~]$ 
[enterprisedb@edb1 ~]$ psql
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
[enterprisedb@edb1 ~]$ 
```

My observations:
1) Some default variables should be improved to catch precise result: `pg_user_home `, `pg_data`, `pg_port`, `pg_version`.
(I find these variables from here: https://github.com/EnterpriseDB/edb-ansible/blob/master/roles/init_dbserver/vars/EPAS_RedHat.yml)

2) It seems that the default unix socket directory of EPAS is not `/tmp`, and this might cause users can not login to the database with `psql` easily with DB account.
So I think the following line (or something similar) should also be included in shell profile.
```
export PGHOST=/var/run/edb/
```
or it might be acceptable to change default socket directory location.

3) The current improve you give relies on experienced PGSQL users to add these to files (shell profile and `.psqlrc`), it would be nice if `edb-ansible` can include default contents, with ready-made variable substitution.

Best Regards.

**Comment by jt-edb** [comment]
Hi,

> But I try to substitute some information with some variables further, I find some other minor issues.

In this case (variable substitutions), the variables `psqlrc_content` and `shell_profile_content` must be defined and passed at `role` level, not in `pre_tasks` block:
```yaml
---
- hosts: all
  name: Postgres deployment playbook
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "EPAS"
[...]

  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: manage_dbserver
      psqlrc_content: |
        \pset null '(NULL)'
        \timing on
      shell_profile_content: |
        ## EnterpriseDB shell environment
        export EDBHOME={{ pg_user_home }}
        export PGDATA={{ pg_data }}
        export PGDATABASE=edb
        export PGUSER=enterprisedb
        export PGPORT={{ pg_port }}
        export PGLOCALEDIR=/usr/edb/{{ pg_version }}/share/locale
        export PGHOST={{ pg_unix_socket_directories[0] }}
        ## Shell Completion enhancement
        shopt -u progcomp

        ## Loading global shell prompt option
        # Source global definitions
        if [ -f /etc/bashrc ]; then
            . /etc/bashrc
        fi
        # Get the aliases and functions
        if [ -f ~/.bashrc ]; then
            . ~/.bashrc
        fi
      when: "'manage_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```

> 1. Some default variables should be improved to catch precise result: `pg_user_home `, `pg_data`, `pg_port`, `pg_version`.
>    (I find these variables from here: https://github.com/EnterpriseDB/edb-ansible/blob/master/roles/init_dbserver/vars/EPAS_RedHat.yml)

It's fixed by the last commit pushed on this PR (https://github.com/EnterpriseDB/edb-ansible/pull/198/commits/8d4242cb9524287d8af7ca94f4c6334f257ec087) and my comment above.

> 2. It seems that the default unix socket directory of EPAS is not `/tmp`, and this might cause users can not login to the database with `psql` easily with DB account.
>    So I think the following line (or something similar) should also be included in shell profile.
> 
> ```
> export PGHOST=/var/run/edb/
> ```
> 
> or it might be acceptable to change default socket directory location.

It can be fixed by adding this to `shell_profile_content`:
```
export PGHOST={{ pg_unix_socket_directories[0] }}
```

> 3. The current improve you give relies on experienced PGSQL users to add these to files (shell profile and `.psqlrc`), it would be nice if `edb-ansible` can include default contents, with ready-made variable substitution.

I have added a default value for `shell_profile_content` in my last commit: https://github.com/EnterpriseDB/edb-ansible/pull/198/commits/8d4242cb9524287d8af7ca94f4c6334f257ec087#diff-89b8831800661fc82987568582c4e04c0062e8e0b14e3e8326d98aab033dd990R23-R28
