### ISSUE TITLE
FATAL: password authentication failed for user "efm"

### ISSUE THREAD

**Issue by Rafles89** [EnterpriseDB/edb-ansible#199]
FATAL: password authentication failed for user "efm" with standby node. Status of standby node is 'Idle'.

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "PG"
        pg_ssl: false
        disable_logging: false
        pg_data: "/opt/pg_data"
        pg_wal: "/opt/pg_data/pg_wal"
        pg_efm_user_password: "efm"
        
         roles:
    - role: setup_repo
    - role: install_dbserver
    - role: init_dbserver
    - role: setup_replication
    - role: setup_efm
    
    
    Inventory:
    
    pgha:
  children:
    primary:
      hosts:
        centos7pg1:
          ansible_host: 192.168.33.12
          private_ip: 192.168.33.12
          hostname: primary
      vars:
        ansible_user: vagrant
    standby:
      hosts:
        centos7pg2:
          ansible_host: 192.168.33.13
          private_ip: 192.168.33.13
          upstream_node_private_ip: 192.168.33.12
          replication_type: asynchronous
          hostname: standby1
      vars:
        ansible_user: vagrant
    pglb:
      hosts:
        centos8pglb:
          ansible_host: 192.168.33.20
          private_ip: 192.168.33.20
      vars:
        ansible_user: vagrant

**Comment by jt-edb** [comment]
Hi,

Just tried a new deployment with a user defined EFM password and I'm not reproducing this issue.

Could you please share the `pg_hba.conf` file content of the 3 nodes?

Thank you,

**Comment by Rafles89** [comment]
Hi,
no problem but I think there is some problem earlier with role 'setup_replication' (or with my configuration of playbook) because user efm is not created on standby node postgres.
There in pg_data directory is not created signal file and both instances looks as primary.

pg_hba.conf (without comments)

local   replication     all     peer
local   all     all     peer
host    replication     repuser 192.168.33.12/32        scram-sha-256
host    replication     repuser 192.168.33.13/32        scram-sha-256
host    replication     all     127.0.0.1/32    scram-sha-256
host    replication     all     ::1/128 scram-sha-256
host    postgres        efm     127.0.0.1/32    scram-sha-256
host    postgres        efm     192.168.33.12/32        scram-sha-256
host    postgres        repuser 192.168.33.12/32        scram-sha-256
host    postgres        repuser 192.168.33.13/32        scram-sha-256
host    postgres        efm     192.168.33.13/32        scram-sha-256
host    all     all     127.0.0.1/32    scram-sha-256
host    all     all     ::1/128 scram-sha-256

Regards

**Comment by jt-edb** [comment]
> no problem but I think there is some problem earlier with role 'setup_replication' (or with my configuration of playbook) because user efm is not created on standby node postgres.
> There in pg_data directory is not created signal file and both instances looks as primary.

Indeed, looks like your standby node does not replicating data. This is probably caused by the `init_dbserver` role that has been applied on the standby node.

Could you try with the following playbook:
```yaml
---
- hosts: all
  name: Postgres deployment playbook
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "PG"
        repo_username: "XXXXXX"
        repo_password: "XXXXXX"
        disable_logging: false
        pg_efm_user_password: "efm"

  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_replication
      when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_efm
      when: "'setup_efm' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```
