### ISSUE TITLE
Failed to start deployed EPAS 13 with `systemctl` due to `/var/run/edb` directory permission changed

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/edb-ansible#202]
Hi, Team,

I test `edb-ansible` to deploy EPAS 13 on CentOS 8-Stream (to mimic RHEL 8.x) with the following inventory YAML and playbook YAML files.
`inventory.yml`
```
---
all:
  children:
    primary:
      hosts:
        edb1:
          ansible_host: 10.208.102.217
          private_ip: 10.208.102.217
    standby:
      hosts:
        edb2:
          ansible_host: 10.208.102.105
          private_ip: 10.208.102.105
          upstream_node_private_ip: 10.208.102.217
          replication_type: asynchronous
```
`playbook.yml`
```
---
- hosts: primary,standby
  name: EDB deployment playbook
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "EPAS"
        repo_username: "ooooo"
        repo_password: "xxxxxx"
        use_hostname: true
        disable_logging: false

  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_replication
      when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: manage_dbserver
      when: "'manage_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```

The primary/standby DBs are created and streaming replication works successfully.

But after I stop and restart my test environments, I find that I can not start with `systemctl start edb-as-13.service` command.

After below investigation, I find that the permission of `/var/run/edb` directory has been changed by `tmpfiles.d`.
```
[root@edb1 ~]# service edb-as-13 start
Redirecting to /bin/systemctl start edb-as-13.service
Job for edb-as-13.service failed because the control process exited with error code.
See "systemctl status edb-as-13.service" and "journalctl -xe" for details.
[root@edb1 ~]# 
[root@edb1 ~]# journalctl -xe --since='2021-07-28 10:50' --until='2021-07-28 11:00'
-- Logs begin at Wed 2021-07-28 01:35:12 UTC, end at Wed 2021-07-28 12:54:21 UTC. --
Jul 28 10:56:25 edb1 systemd[1]: edb-as-13.service: Failed to reset de
vices.list: Operation not permitted
Jul 28 10:56:25 edb1 systemd[1]: Starting EDB Postgres Advanced Server 13...
-- Subject: Unit edb-as-13.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit edb-as-13.service has begun starting up.
Jul 28 10:56:26 edb1 edb-postmaster[1234]: 2021-07-28 10:56:26.789 UTC [12341] @ app= LOG:  directory "edb_wait_states" already exists
Jul 28 10:56:27 edb1 edb-postmaster[1234]: 2021-07-28 10:56:27.032 UTC [12342] @ app= LOG:  redirecting log output to logging collector process
Jul 28 10:56:27 edb1 edb-postmaster[1234]: 2021-07-28 10:56:27.032 UTC [12343] @ app= HINT:  Future log output will appear in directory "/var/log/edb".
Jul 28 10:56:27 edb1 systemd[1]: edb-as-13.service: Main process exited, code=exited, status=1/FAILURE
Jul 28 10:56:27 edb1 systemd[1]: edb-as-13.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit edb-as-13.service has entered the 'failed' state with result 'exit-code'.
Jul 28 10:56:27 edb1 systemd[1]: Failed to start EDB Postgres Advanced
 Server 13.
-- Subject: Unit edb-as-13.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit edb-as-13.service has failed.
-- 
-- The result is failed.
Jul 28 10:56:46 edb1 su[1241]: (to enterprisedb) root on pts/0
Jul 28 10:56:46 edb1 su[1241]: pam_systemd(su-l:session): Cannot create session: Already running in a session or user slice
Jul 28 10:56:46 edb1 su[1241]: pam_unix(su-l:session): session opened for user enterprisedb by (uid=0)
Jul 28 10:57:03 edb1 su[1241]: pam_unix(su-l:session): session closed for user enterprisedb
[root@edb1 ~]# 
[root@edb1 ~]# ls /var/log/edb/
as13                       edb-2021-07-28_013528.log  pgagent12
edb-2021-07-27_165643.log  edb-2021-07-28_105627.log  pgagent13
[root@edb1 ~]# cat /var/log/edb/edb-2021-07-28_105627.log 
2021-07-28 10:56:27.033 UTC [12344] @ app= LOG:  starting PostgreSQL 13.3 (EnterpriseDB Advanced Server 13.3.7) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit
2021-07-28 10:56:27.033 UTC [12345] @ app= LOG:  listening on IPv4 address "0.0.0.0", port 5444
2021-07-28 10:56:27.033 UTC [12346] @ app= LOG:  listening on IPv6 address "::", port 5444
2021-07-28 10:56:27.035 UTC [12347] @ app= FATAL:  could not create lock file "/var/run/edb/.s.PGSQL.5444.lock": Permission denied
2021-07-28 10:56:27.041 UTC [12348] @ app= LOG:  database system is shut down
[root@edb1 ~]# ls -l /var/run/
total 16
-rw-------  1 root root    0 Jul 28 01:35 agetty.reload
drwxr-xr-x  2 root root   40 Jul 28 01:35 console
----------  1 root root    0 Jul 28 01:35 cron.reboot
drwx------  2 root root   40 Jul 28 01:35 cryptsetup
drwxr-xr-x  2 root root   60 Jul 28 01:35 dbus
-rw-r--r--  1 root root    4 Jul 28 01:35 dhclient-eth0.pid
drwxr-xr-x  4 root root   80 Jul 28 01:35 edb
drwxr-xr-x  2 root root   40 Jul 28 01:35 faillock
prw-------  1 root root    0 Jul 28 01:35 initctl
drwxr-xr-x  3 root root   60 Jul 28 01:35 lock
drwxr-xr-x  3 root root   60 Jul 28 01:35 log
-rw-------  1 root root    3 Jul 28 01:35 rsyslogd.pid
drwxr-xr-x  2 root root   40 Jul 28 01:35 sepermit
drwxr-xr-x  2 root root   40 Jul 28 01:35 setrans
-rw-r--r--  1 root root    4 Jul 28 01:35 sshd.pid
drwx--x--x  3 root root   60 Jul 28 01:35 sudo
drwxr-xr-x 18 root root  480 Jul 28 10:56 systemd
drwxr-xr-x  4 root root  100 Jul 28 01:35 udev
drwxr-xr-x  3 root root   60 Jul 28 10:40 user
-rw-rw-r--  1 root utmp 1152 Jul 28 01:35 utmp
[root@edb1 ~]# ls -l /var/run/edb/
total 0
drwxr-xr-x 2 enterprisedb enterprisedb 40 Jul 28 01:35 as13
drwxr-xr-x 2 enterprisedb enterprisedb 40 Jul 28 01:35 pgagent12
[root@edb1 ~]# 
```

It seems that tmpfiles.d provided by EPAS 13 points to the sub-directory `/var/run/edb/as13/`
```
[root@edb1 ~]# ls /usr/lib/tmpfiles.d/
cryptsetup.conf  edb-pgagent-13.conf  legacy.conf      portables.conf        systemd.conf
dbus.conf        etc.conf             libselinux.conf  rpm.conf              tmp.conf
dnf.conf         home.conf            openssh.conf     sudo.conf             var.conf
edb-as-13.conf   journal-nocow.conf   pam.conf         systemd-nologin.conf  x11.conf
[root@edb1 ~]# ls /usr/lib/tmpfiles.d/edb-as-13.conf 
/usr/lib/tmpfiles.d/edb-as-13.conf
[root@edb1 ~]# cat /usr/lib/tmpfiles.d/edb-as-13.conf 
d /var/run/edb/as13 0755 enterprisedb enterprisedb -
d /var/lock/edb/as13 0755 enterprisedb enterprisedb -
d /var/log/edb/as13 0755 enterprisedb enterprisedb -
[root@edb1 ~]# 
```

So I correct it with the following steps without affecting future package update, and successfully start DB service.
```
[root@edb1 ~]# cp /usr/lib/tmpfiles.d/edb-as-13.conf /etc/tmpfiles.d/
[root@edb1 ~]# echo 'd /var/run/edb 0755 enterprisedb enterprisedb -' >> /etc/tmpfiles.d/edb-as-13.conf
[root@edb1 ~]# systemd-tmpfiles --create --boot 
[/etc/tmpfiles.d/edb-as-13.conf:1] Line references path below legacy directory /var/run/, updating /var/run/edb/as13 → /run/edb/as13; please update the tmpfiles.d/ drop-in file accordingly.
[/etc/tmpfiles.d/edb-as-13.conf:4] Line references path below legacy directory /var/run/, updating /var/run/edb → /run/edb; please update the tmpfiles.d/ drop-in file accordingly.
[/usr/lib/tmpfiles.d/edb-pgagent-13.conf:1] Line references path below legacy directory /var/run/, updating /var/run/edb/pgagent12 → /run/edb/pgagent12; please update the tmpfiles.d/ drop-in file accordingly.
[root@edb1 ~]# ls /var/run/ -l    
total 16
-rw-------  1 root         root           0 Jul 28 01:35 agetty.reload
drwxr-xr-x  2 root         root          40 Jul 28 01:35 console
----------  1 root         root           0 Jul 28 01:35 cron.reboot
drwx------  2 root         root          40 Jul 28 01:35 cryptsetup
drwxr-xr-x  2 root         root          60 Jul 28 01:35 dbus
-rw-r--r--  1 root         root           4 Jul 28 01:35 dhclient-eth0.pid
drwxr-xr-x  4 enterprisedb enterprisedb  80 Jul 28 01:35 edb
drwxr-xr-x  2 root         root          40 Jul 28 01:35 faillock
prw-------  1 root         root           0 Jul 28 01:35 initctl
drwxr-xr-x  4 root         root          80 Jul 28 13:13 lock
drwxr-xr-x  3 root         root          60 Jul 28 01:35 log
-rw-r--r--  1 root         root         142 Jul 28 13:13 nologin
-rw-------  1 root         root           3 Jul 28 01:35 rsyslogd.pid
drwxr-xr-x  2 root         root          40 Jul 28 01:35 sepermit
drwxr-xr-x  2 root         root          40 Jul 28 01:35 setrans
-rw-r--r--  1 root         root           4 Jul 28 01:35 sshd.pid
drwx--x--x  3 root         root          60 Jul 28 01:35 sudo
drwxr-xr-x 18 root         root         480 Jul 28 10:56 systemd
drwxr-xr-x  4 root         root         100 Jul 28 01:35 udev
drwxr-xr-x  3 root         root          60 Jul 28 10:40 user
-rw-rw-r--  1 root         utmp           0 Jul 28 13:13 utmp
[root@edb1 ~]# 
[root@edb1 ~]# service edb-as-13 start
Redirecting to /bin/systemctl start edb-as-13.service
[root@edb1 ~]# 
```

Can you help improving `edb-ansible` to handle this scenario?

Best Regards.
