### ISSUE TITLE
efm and streaming replication using replication slots PG12

### ISSUE THREAD

**Issue by htcosta** [EnterpriseDB/edb-ansible#260]
**Problem:**
After deploying an PG12 cluster, promote the standby replica to become a primary node using efm.
`efm promote <cluster> -switchover` 

Standby databases is not in sync with the primary database, is this the expected behaviour ?
This does not happen when deploying a PG13 cluster.

**output**
```shell
Cluster Status: tst

        Agent Type  Address              DB       VIP
        ----------------------------------------------------------------
        Standby    db01.internal      UP       192.168.100.60
        Primary    db02.internal      UP       192.168.100.60*
        Witness    barman.internal    N/A      192.168.100.60

Allowed node host list:
        db02.internal db01.internal barman.internal

Membership coordinator: barman.internal

Standby priority host list:
        db01.internal

Promote Status:

        DB Type     Address              WAL Received LSN   WAL Replayed LSN   Info
        ---------------------------------------------------------------------------
        Primary     db02.internal                                        0/90001B8
        Standby     db01.internal             0/9000000                  0/90000A0

        One or more standby databases are not in sync with the primary database. The following node(s) returned a WAL LSN that does not match the primary: db01.internal

```

**Files**

```yaml
# deployment.yml
---
- hosts: all
  name: HA Postgres Deployment
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_instance_name: "tst"
        pg_version: 12
        pg_type: "PG"
        pg_port: 5433
        pem_pg_port: 5433
        cert_common_name: "PG"
        cert_country: "NL"
        cert_state: "ZH"
        cert_city: "ROTTERDAM"
        cert_org_unit: "TEST"
        cert_email: "test@test.internal"
        efm_parameters:
          - name: user.email
            value: "test@test.internal"
          - name: virtual.ip
            value: "192.168.100.60"
          - name: virtual.ip.interface
            value: "enp1s0"
          - name: virtual.ip.prefix
            value: "24"
          - name: virtual.ip.single
            value: "true"
          - name: ping.server.ip
            value: "192.168.100.1"
        repo_username: "<name>"
        repo_password: "<pass>"
        disable_logging: false
        ssd_disk: yes

  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_replication
      when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_efm
      when: "'setup_efm' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_pemserver
      when: "'setup_pemserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_pemagent
      when: "'setup_pemagent' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_barmanserver
      when: "'setup_barmanserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_barman
      when: "'setup_barman' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: autotuning
      when: "'autotuning' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
...
```

```yaml
# inventory
---
all:
  children:
    pemserver:
      hosts:
        pem.internal:
          ansible_host: 192.168.100.64
          private_ip: 192.168.100.64
          hostname: pem.internal
    barmanserver:
      hosts:
        barman.internal:
          ansible_host: 192.168.100.63
          private_ip: 192.168.100.63
          hostname: barman.internal
    primary:
      hosts:
        db01.internal:
          ansible_host: 192.168.100.61
          private_ip: 192.168.100.61
          barman: true
          barman_server_private_ip: 192.168.100.63
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 192.168.100.64
          hostname: db01.internal
    standby:
      hosts:
        db02.internal:
          ansible_host: 192.168.100.62
          private_ip: 192.168.100.62
          upstream_node_private_ip: 192.168.100.61
          replication_type: synchronous
          barman: true
          barman_server_private_ip: 192.168.100.63
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 192.168.100.64
          hostname: db02.internal
    witness:
      hosts:
        barman.internal:
          ansible_host: 192.168.100.63
          private_ip: 192.168.100.63
          upstream_node_private_ip: 192.168.100.61
          hostname: barman.internal
...
```

**Comment by htcosta** [comment]
For some reason on the PG12 deployment the efm parameter `update.physical.slots.period` after the deployment is "0" , that is not the case in the PG13 deployment which respects the default value of "5".

**Comment by htcosta** [comment]
**efm_configure.yml**

```yaml
- name: Prepare final parameters list
  set_fact:
    efm_node_parameters: "{{ efm_node_parameters + efm_physical_slot_param }}"
  when:
    - (pg_version|int > 11 and pg_type == "EPAS") or (pg_version|int > 12 and pg_type == "PG")
    - efm_version|int > 3.10
```

Is there a reason for this ?
