### ISSUE TITLE
Cannot install community postgres

### ISSUE THREAD

**Issue by MichaelDBA** [EnterpriseDB/edb-ansible#262]
I run a playbook that uses this EDB collection but it says "skipping".

```
PG@13> ansible-playbook playbooks/initialize_pg.yml

PLAY [Postgres deployment playbook] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [192.168.1.144]
ok: [192.168.1.133]

TASK [Initialize the user defined variables] ************************************************************************************************************************************************************************************************
ok: [192.168.1.133]
ok: [192.168.1.144]

TASK [edb_devops.edb_postgres.setup_repo : Include the setup_repo.yml] **********************************************************************************************************************************************************************
skipping: [192.168.1.144]
skipping: [192.168.1.133]

TASK [edb_devops.edb_postgres.install_dbserver : Include the install_dbserver.yml] **********************************************************************************************************************************************************
skipping: [192.168.1.133]
skipping: [192.168.1.144]

TASK [edb_devops.edb_postgres.init_dbserver : Include the init_dbserver.yml] ****************************************************************************************************************************************************************
skipping: [192.168.1.133]
skipping: [192.168.1.144]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
192.168.1.133              : ok=2    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
192.168.1.144              : ok=2    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0

```

**Comment by vibhorkumar123** [comment]
Can you please share your inventory.yml and initialize_pg.yml?

**Comment by MichaelDBA** [comment]
**initialize_pg_yml contents:**
```
---
- hosts: prod_dbs
  name: Postgres deployment playbook
  become: yes
  gather_facts: yes
  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "PG"
        pg_data: /data
        repo_username: "postgres"
        repo_password: "mypass"
        pg_superuser: "postgres"
        pg_superuser_password: "mypass"
        disable_logging: false

  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: init_dbserver
      when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"

```

**inventory file contents:**
```
---
all_dbs:
  children:
    prod_dbs:
      hosts:
        192.168.1.133:
        192.168.1.144:
    dev_dbs:
      hosts:
        192.168.1.999:


```

**Comment by MichaelDBA** [comment]
I tried reconstructing the hosts file to make it work according to the pattern described above, but I cannot get it to work for me.  Can you try to reconstruct my simple hosts file so I can try it?

**Comment by MichaelDBA** [comment]
I can't seem to get it to work based off your example above.  Can you suggest based on my existing host file?

**Comment by vibhorkumar123** [comment]
Hi @MichaelDBA, below is an example based on your inventory.yml file.
```
all:
  children:
    primary:
      hosts:
         prod_dbs_host1:
            ansible_host: 192.168.1.133
            private_ip: 192.168.1.133
         prod_dbs_host2:
            ansible_host: 192.168.1.144
            private_ip: 192.168.1.144
         dev_dbs_host1:
            ansible_host: 192.168.1.199
            private_ip: 192.168.1.199
```
