### ISSUE TITLE
allow skip of linux_update_etc_hosts.yml

### ISSUE THREAD

**Issue by baran81** [EnterpriseDB/edb-ansible#306]
Hi
near al role run this block if variable "use_hostname"

linux_update_etc_hosts.yml modify the /etc/hosts of the machine and the hostname system configuration.

This can impact other tools running on the host, that maybe need a long hostname when you use short, or need both fqdn and short hostname in the /etc/hosts

please add an option to skip this step (maybe a skip_etc_hosts variable or so)

regards

**Comment by vibhorkumar123** [comment]
You could add include names in playbook.yml.   Something like given below:
```
all:
  children:
    pemserver:
      hosts:
        east-pemserver.pem.domain:
          ansible_host: xxx.xxx.xxx.xxx
          private_ip: xxx.xxx.xxx.xxx
    primary:
      hosts:
        east-primary1-pg.domain:
          ansible_host: xxx.xxx.xxx.xxx
          private_ip: xxx.xxx.xxx.xxx
          pem_agent: true
          pem_server_private_ip: xxx.xxx.xxx.xxx
    standby:
      hosts:
        east-standby1-pg.domain:
          ansible_host: xxx.xxx.xxx.xxx
          private_ip: xxx.xxx.xxx.xxx
          upstream_node_private_ip: xxx.xxx.xxx.xxx
          replication_type: synchronous
          pem_agent: true
          pem_server_private_ip: xxx.xxx.xxx.xxx
     ...
```
