### ISSUE TITLE
Defining empty pg_version in OS specific vars breaks expected Ansible behaviour

### ISSUE THREAD

**Issue by stroobl** [EnterpriseDB/edb-ansible#314]
I noticed that in the setup_efm role you define and empty variable pg_version:
```
> grep 'pg_version:' vars/*
vars/EPAS_Debian.yml:pg_version: ""
vars/EPAS_RedHat.yml:pg_version: ""
vars/PG_Debian.yml:pg_version: ""
vars/PG_RedHat.yml:pg_version: ""
```
This is not a good idea, since variables defined at that level are  ([very hard to override](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)). It would be much better to leave the variable undefined at that point. Right now you can only use set_fact or -e at the playbook level to override that empty string. It would be much more elegant is pg_version can be defined as a normal inventory variable so that you don't need a different playbook if you want to deploy a different EDB/PG version.

I ran some tests with the facts you set in the example playbook and pg_version is the only one that requires set_fact right now. For all the others it's possible to define them as normal inventory variables.
```
  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 14
        pg_type: "EPAS"
        repo_username: "<edb-package-repository-username>"
        repo_password: "<edb-package-repository-password>"
        disable_logging: false
```
