### ISSUE TITLE
Question: Define local WAL Archive?

### ISSUE THREAD

**Issue by dirkcaumueller** [EnterpriseDB/edb-ansible#322]
Dear EDB team!

I can't find a configuration parameter to define and create a local WAL archive directory. Is this true (because usually Barman's WAL archiving feature is the way to go)?

Looks like only roles `init_dbserver` and `setup_replication` require some modifications. I'm willing to contribute/implement this feature.

Best regards,
Dirk

**Comment by vibhorkumar123** [comment]
You can use `pg_postgres_conf_params` variable for setting `archive_command` after creating a cluster.
https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/manage_dbserver

**Comment by dirkcaumueller** [comment]
Thank you for your reply.

I'm aware of the `pg_postgres_conf_params` option for setting the `archive_command`. The only way without having to write a separate playbook, as far as I understand, is to create the corresponding directory in the filesystem by adding `mkdir -p /path/to/wal_archive && ...` as part of the `archive_command`. 

So, what I really mean with my question is an Ansible parameter (e.g. in the default `main.yml` of a role) to create the directory in the filesystem. A parameter like:

```yml
pg_wal_archive: ""
```

and a task to create it, like:

```yml
- name: Ensure postgres wal archive directory exists
  file:
    path: "{{ pg_wal_archive }}"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory
  become: yes
  when: pg_wal_archive|length > 0
```

I hope my question is now better understandable. What do you think?
