### ISSUE TITLE
Hi! I want to deploy repmgr with the following configuration

### ISSUE THREAD

**Issue by z3473** [EnterpriseDB/edb-ansible#488]
[root@localhost playbook]# cat install_test_repmgr_postgresql.yml 
---
- hosts: primary,standby
  name: Install and configure Repmgr
  become: true
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_type: "PG"
        pg_version: 14

        repmgr_failover: automatic
        repmgr_reconnect_attemps: 2
        repmgr_reconnect_interval: 2

  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
    - setup_replication
    - setup_repmgr
    
[root@localhost playbook]# cat inventory.yml 
all:
  children:
    primary:
      hosts:
        primary1:
          ansible_host: 192.168.2.114
          private_ip: 192.168.2.114
    standby:
      hosts:
        standby1:
          ansible_host: 192.168.2.115
          private_ip: 192.168.2.115
          upstream_node_private_ip: 192.168.2.115
          replication_type: synchronous
        standby2:
          ansible_host: 192.168.2.117
          private_ip: 192.168.2.117
          upstream_node_private_ip: 192.168.2.117
          replication_type: asynchronous
[root@localhost playbook]# ansible-playbook install_test_repmgr_postgresql.yml -i inventory.yml
TASK [edb_devops.edb_postgres.setup_replication : Gather the cluste_nodes information] **************************************************************************
fatal: [primary1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.pg_sr_cluster_nodes'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Inventory error with the following standbys nodes [u'standby1', u'standby2']. Upstream node is not configured or not found"}
fatal: [standby1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.pg_sr_cluster_nodes'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Inventory error with the following standbys nodes [u'standby1', u'standby2']. Upstream node is not configured or not found"}
fatal: [standby2]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.pg_sr_cluster_nodes'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Inventory error with the following standbys nodes [u'standby1', u'standby2']. Upstream node is not configured or not found"}

PLAY RECAP ******************************************************************************************************************************************************
primary1                   : ok=51   changed=17   unreachable=0    failed=1    skipped=70   rescued=0    ignored=0   
standby1                   : ok=47   changed=17   unreachable=0    failed=1    skipped=70   rescued=0    ignored=0   
standby2                   : ok=47   changed=17   unreachable=0    failed=1    skipped=70   rescued=0    ignored=0 

I'm not sure where the error is, how do I fix it? Also, what does "upstream_node_private_ip" refer to?

**Comment by jt-edb** [comment]
Hi,

> I'm not sure where the error is, how do I fix it? Also, what does "upstream_node_private_ip" refer to?

`upstream_node_private_ip` refers to the private IP of the primary node, which is `192.168.2.114` in your case.

**Comment by z3473** [comment]
@jt-edb Hi! I have reworked the configuration. But there is another error.
[root@localhost playbook]# cat install_test_repmgr_postgresql.yml
---
- hosts: primary,standby
  name: Install and configure Repmgr
  become: true
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_type: "PG"
        pg_version: 14

        repmgr_failover: automatic
        repmgr_reconnect_attemps: 2
        repmgr_reconnect_interval: 2

  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
#    - setup_replication
    - setup_repmgr
[root@localhost playbook]# cat inventory.yml
all:
  children:
    primary:
      hosts:
        primary1:
          ansible_host: 192.168.2.114
          private_ip: 192.168.2.114
    standby:
      hosts:
        standby1:
          ansible_host: 192.168.2.115
          private_ip: 192.168.2.115
          upstream_node_private_ip: 192.168.2.115

[root@localhost playbook]# ansible-playbook install_test_repmgr_postgresql.yml -i inventory.yml -vvvv
TASK [edb_devops.edb_postgres.setup_repmgr : Set repmgr_cluster_nodes] ******************************************************************************************
task path: /root/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repmgr/tasks/setup_repmgr.yml:20
fatal: [primary1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.repmgr_nodes'. Error was a <type 'exceptions.KeyError'>, original message: u'192.168.2.115'"
}
fatal: [standby1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.repmgr_nodes'. Error was a <type 'exceptions.KeyError'>, original message: u'192.168.2.115'"
}

PLAY RECAP ******************************************************************************************************************************************************
primary1                   : ok=47   changed=2    unreachable=0    failed=1    skipped=70   rescued=0    ignored=0   
standby1                   : ok=43   changed=2    unreachable=0    failed=1    skipped=70   rescued=0    ignored=0

**Comment by jt-edb** [comment]
Please update `upstream_node_private_ip` to `192.168.2.114`

**Comment by z3473** [comment]
@jt-edb "upstream_node_private_ip"refers to the ip of the PRIMARY node？
      ”private_ip:“refers to the ip of each node？

**Comment by jt-edb** [comment]
> "upstream_node_private_ip"refers to the ip of the PRIMARY node？
> ”private_ip:“refers to the ip of each node？

Correct.

**Comment by z3473** [comment]
@jt-edb The currently loaded roles, but running playbook reports an error, "$libdir/edb_pg_tuner" where is defined, which roles need to be used？

[root@localhost playbook]# cat install_test_repmgr_postgresql.yml
---
- hosts: primary,standby
  name: Install and configure Repmgr
  become: true
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_type: "PG"
        pg_version: 14

        repmgr_failover: automatic
        repmgr_reconnect_attemps: 2
        repmgr_reconnect_interval: 2

  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
    - setup_repmgr

#TASK [edb_devops.edb_postgres.init_dbserver : Enable and start systemd service] *********************************************************************************
fatal: [standby1]: FAILED! => {"changed": false, "msg": "Unable to start service postgresql-14: Job for postgresql-14.service failed because the control process exited with error code. See \"systemctl status postgresql-14.service\" and \"journalctl -xe\" for details.\n"}
fatal: [primary1]: FAILED! => {"changed": false, "msg": "Unable to start service postgresql-14: Job for postgresql-14.service failed because the control process exited with error code. See \"systemctl status postgresql-14.service\" and \"journalctl -xe\" for details.\n"}

PLAY RECAP ******************************************************************************************************************************************************
primary1                   : ok=37   changed=15   unreachable=0    failed=1    skipped=33   rescued=0    ignored=0   
standby1                   : ok=37   changed=15   unreachable=0    failed=1    skipped=33   rescued=0    ignored=0 

#Mar 01 16:09:54 primary1 postmaster[2955]: 2023-03-01 16:09:54.702 CST [29551] @ app= FATAL:  could not access file "$libdir/edb_pg_tuner": No such file or direc
Mar 01 16:09:54 primary1 postmaster[2955]: 2023-03-01 16:09:54.702 CST [29552] @ app= LOG:  database system is shut down
Mar 01 16:09:54 primary1 polkitd[651]: Unregistered Authentication Agent for unix-process:2944:139254 (system bus name :1.69, object path /org/freedesktop/Policy
Mar 01 16:09:54 primary1 systemd[1]: postgresql-14.service: main process exited, code=exited, status=1/FAILURE
Mar 01 16:09:54 primary1 sudo[2900]: pam_unix(sudo:session): session closed for user root

"$libdir/edb_pg_tuner"

**Comment by jt-edb** [comment]
Please update to 3.17.2, this issue has been recently fixed.

**Comment by jt-edb** [comment]
You have to set the `pg_ssl` variable to `false`:

```yaml
- hosts: primary,standby
  name: Install and configure Repmgr
  become: true
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_type: "PG"
        pg_version: 14

        repmgr_failover: automatic
        repmgr_reconnect_attemps: 2
        repmgr_reconnect_interval: 2
        # Do not use EDB's repo and use community repos only
        enable_edb_repo: false
        # Do not set up SSL for Postgres
        pg_ssl: false

  roles:
  - setup_repo
  - install_dbserver
  - init_dbserver
  - setup_repmgr
```

**Comment by z3473** [comment]
@jt-edb Thanks! When I run this playbook the following error occurs.

TASK [edb_devops.edb_postgres.setup_repmgr : Register repmgr node] **********************************************************************************************
fatal: [standby1]: FAILED! => {"changed": true, "cmd": "set -o pipefail\n/usr/pgsql-14/bin/repmgr  -f /etc/repmgr/14/repmgr-main.conf  standby register -F &>> /var/log/repmgr/register.log\n", "delta": "0:00:00.017563", "end": "2023-03-01 17:55:07.654564", "msg": "non-zero return code", "rc": 1, "start": "2023-03-01 17:55:07.637001", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [edb_devops.edb_postgres.setup_repmgr : Register the repmgr witness nodes] *********************************************************************************
skipping: [primary1]

TASK [edb_devops.edb_postgres.setup_repmgr : Include generate_ssh_keys.yml] *************************************************************************************
included: /root/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repmgr/tasks/generate_ssh_keys.yml for primary1

TASK [edb_devops.edb_postgres.setup_repmgr : Ensure the directory pg_user_home/.ssh exists] *********************************************************************
changed: [primary1]

TASK [edb_devops.edb_postgres.setup_repmgr : Check if the SSH private key exists] *******************************************************************************
ok: [primary1]

TASK [edb_devops.edb_postgres.setup_repmgr : Ensure Postgres owner's SSH keys exist] ****************************************************************************
changed: [primary1]

TASK [edb_devops.edb_postgres.setup_repmgr : Include exchange_ssh_keys.yml] *************************************************************************************
skipping: [primary1] => (item={u'inventory_hostname': u'primary1', u'replication_type': None, u'hostname': u'primary1', u'upstream_node_private_ip': None, u'ansible_host': u'192.168.2.114', u'node_type': u'primary', u'private_ip': u'192.168.2.114', u'id': 1}) 
included: /root/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repmgr/tasks/exchange_ssh_keys.yml for primary1

TASK [edb_devops.edb_postgres.setup_repmgr : Set _local_host and _remote_host when using hostname] **************************************************************
ok: [primary1]

TASK [edb_devops.edb_postgres.setup_repmgr : Set _local_host and _remote_host when not using hostname] **********************************************************
skipping: [primary1]

TASK [edb_devops.edb_postgres.setup_repmgr : Fetch remote server SSH public key] ********************************************************************************
fatal: [primary1 -> standby1]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/pgsql/.ssh/id_rsa.pub"}

PLAY RECAP ******************************************************************************************************************************************************
primary1                   : ok=102  changed=35   unreachable=0    failed=1    skipped=87   rescued=0    ignored=0   
standby1                   : ok=79   changed=28   unreachable=0    failed=1    skipped=82   rescued=0    ignored=0

**Comment by jt-edb** [comment]
Oh, we must include the `setup_replication` role before setting up repmgr:
```yaml
- hosts: primary,standby
  name: Install and configure Repmgr
  become: true
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_type: "PG"
        pg_version: 14

        repmgr_failover: automatic
        repmgr_reconnect_attemps: 2
        repmgr_reconnect_interval: 2
        # Do not use EDB's repo and use community repos only
        enable_edb_repo: false
        # Do not set up SSL for Postgres
        pg_ssl: false

  roles:
  - setup_repo
  - install_dbserver
  - init_dbserver
  - setup_replication
  - setup_repmgr
```

**Comment by jt-edb** [comment]
Actually, the correct playbook content should be:

```yaml
- hosts: all
  name: Install and configure Repmgr
  become: true
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_type: "PG"
        pg_version: 14

        repmgr_failover: automatic
        repmgr_reconnect_attemps: 2
        repmgr_reconnect_interval: 2
        # Do not use EDB's repo and use community repos only
        enable_edb_repo: false
        # Do not set up SSL for Postgres
        pg_ssl: false

  roles:
  - role: setup_repo
    when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
  - role: install_dbserver
    when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
  - role: init_dbserver
    when: "'init_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
  - role: setup_replication
    when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
  - role: setup_repmgr
    when: "'setup_repmgr' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```
