### ISSUE TITLE
Error when trying to setup pgbackrest server

### ISSUE THREAD

**Issue by Sagebati** [EnterpriseDB/edb-ansible#537]
Hi, 

I'm trying to setup a pgbackrest server. but I get 

```
TASK [edb_devops.edb_postgres.setup_pgbackrestserver : Build pgbackrest_conf_lines] *****************************************************************************************************************************************************************************************************************************************
fatal: [util3]: FAILED! => {"msg": "'pgbackrest_standby_configuration' is undefined. 'pgbackrest_standby_configuration' is undefined"}
```

here is my playbook 

```yaml
- hosts: pgbackrestserver
  name: Deploy pgbackrest servers
  become: true
  gather_facts: true
  collections:
    - edb_devops.edb_postgres
  pre_tasks:
    - name: Initialize the user defined variables
      ansible.builtin.set_fact:
        pg_version: 14
        pg_type: "PG"
        repo_cipher_password: "password"
        repo_retention_full_type: "count"
        repo_retention_full: 2
  roles:
    - role: setup_repo
      when: "'setup_repo' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_pgbackrestserver
      when: "'setup_pgbackrestserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
```

```yaml
all:
    vars:
        ansible_python_interpreter: /usr/bin/python3
        enable_edb_repo: false
    children:
        dbservers:
            hosts:
                util2:
                    ansible_host: util2
                    ansible_hostname: dbserver1
                    ansible_user: ubuntu
                    ansible_port: 22
                    private_ip: xxxxxxxxx
                    hostname: util2
                    pgbackrest: true
                    pgbackrest_server_private_ip: xxxxxxxx
                util3:
        pgbackrestserver:
            hosts:
                util3:
                    ansible_host: util3
                    ansible_hostname: pgbackrest1
                    private_ip: xxxxxxxxx
                    ansible_user: ubuntu
                    ansible_port: 22
                    hostname: util3
        primary:
            hosts:
                util2:
        standby:
            hosts:
                util3:
```

any ideas ?
