### ISSUE TITLE
Move with_dict servers in the roles to manage and iteration of roles' tasks 

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/edb-ansible#6]
Currently, users need to add with_dict as given below in the playbook to use the roles. 
```
    - name: Iterate through repo role with items from hosts file
      include_role:
        name: setup_repo
      with_dict: "{{ servers }}"
```
It will be simpler if we can skip using with_dict in the playbook. Something like given below:
```
roles:
   setup_repo
```
